/*
 * Copyright (c) 2024-2026 Tom Rodriguez ("Toasty") — <toasty@heroiclands.org>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/** Bounded identities and standalone credit forms shared with the commit hooks. */
export const identities = [
    "Codex",
    "ChatGPT",
    "OpenAI",
    "OpenAI Codex",
    "OpenAI ChatGPT",
    "Claude",
    "Claude Code",
    "Anthropic",
    "GitHub Copilot",
    "Gemini",
    "Cursor",
    "AI",
    "AI assistant",
    "an AI assistant",
];
export const phrases = ["Generated by", "Generated with", "Assisted by", "Written by"];
export const mailboxes = [
    "codex@openai.com",
    "chatgpt@openai.com",
    "noreply@openai.com",
    "claude@anthropic.com",
    "noreply@anthropic.com",
];
const identity = new RegExp(`^(?:${identities.join("|")})$`, "i");
const signature = new RegExp(`^(?:${phrases.join("|")})\\s+(.+?)[.!]?$`, "i");

/** Normalize decoration while keeping each character's original UTF-16 offset. */
function normalize(line) {
    let chars = Array.from({ length: line.length }, (_, offset) => ({
        text: line[offset],
        offset,
    }));
    const replace = (pattern, keep) => {
        const text = chars.map((char) => char.text).join("");
        const matches = [...text.matchAll(pattern)];
        for (const match of matches.reverse()) {
            const retained = keep(match);
            chars.splice(
                match.index,
                match[0].length,
                ...chars.slice(match.index + retained.start, match.index + retained.end),
            );
        }
    };
    replace(/\[([^\]]+)\]\([^\s)]*\)/g, (match) => ({ start: 1, end: 1 + match[1].length }));
    replace(/[*_`~]/g, () => ({ start: 0, end: 0 }));
    replace(/^[^\p{L}]+/gu, () => ({ start: 0, end: 0 }));
    return {
        text: chars
            .map((char) => char.text)
            .join("")
            .trimEnd(),
        column: (chars[0]?.offset ?? 0) + 1,
    };
}

/** Find a complete credit clause; ordinary prose and human identities pass. */
export function attribution(line) {
    const normalized = normalize(line);
    const trailer = normalized.text.match(/^co-authored-by:\s*(.*?)\s*(?:<([^<>]+)>)?$/i);
    if (trailer && (identity.test(trailer[1]) || mailboxes.includes(trailer[2]?.toLowerCase()))) {
        return { column: normalized.column, kind: "Co-Authored-By trailer naming an assistant" };
    }
    const credit = normalized.text.match(signature);
    const generic = normalized.text.match(
        /^AI-(?:assisted|generated)(?:\s+(?:by|with)\s+(.+?))?[.!]?$/i,
    );
    if (
        (credit && identity.test(credit[1])) ||
        (generic && (!generic[1] || identity.test(generic[1])))
    ) {
        return { column: normalized.column, kind: "assistant signature" };
    }
    return null;
}
